"""add servings column

Revision ID: 582a8dd41ee5
Revises: 001
Create Date: 2025-09-19 14:16:36.234156

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "582a8dd41ee5"
down_revision = "001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipes", sa.Column("servings", sa.Integer(), nullable=True))
    op.execute("UPDATE recipes SET servings = 6 WHERE servings IS NULL")
    op.alter_column("recipes", "servings", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipes", "servings")
    # ### end Alembic commands ###
